server:
  port: 8890
spring:
  application:
    name: niit-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/hainan?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.justin.niituserservice.domain
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    metadata-map: MAIN