spring:
  application:
    name: niit-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jackie2330489/cruddemo
          search-paths: yml
          default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.1.75:8888/eureka/
server:
  port: 8889

